---
- name: Start server
  hosts: localhost
  roles:
    - { role: server, srv_name: WP-POC, src_template: ubuntu-14-64, srv_public: true, srv_ports: [80, 443] }

- name: Install Bitnami WordPress
  hosts: servers
  vars_file:
    - bitnami.yml
  tasks:
    - name: Download Bitnami {{ package.name }} installer
      get_url:
        url: {{ package.installer.url }}
        dest: {{ sandbox_dir}}/{{ package.installer.file }}
        mode: "u+rwx"

    - name: Install {{ package.name }} on server
      script: {{ sandbox_dir }}/{{ package.installer.file }} --prefix {{ install_dir }}
