---
- name: Start server
  hosts: localhost
  roles:
    - { role: server, srv_name: WP-POC, src_template: ubuntu-14-64, srv_public: true, srv_ports: [22, 80, 443] }

- name: Update to latest Python 2.7
  hosts: servers
  roles:
    - install-python-2.7.12

- name: Install Bitnami WordPress
  hosts: servers
  vars_files:
    - bitnami.yml
  tasks:
    - name: Download Bitnami WordPress installer
      get_url:
        url: "{{ package.installer.url }}"
        dest: "{{ sandbox_dir}}/{{ package.installer.file }}"
        mode: "u+rwx"

    - name: Install WordPress on server
      script: "{{ sandbox_dir }}/{{ package.installer.file }} --prefix {{ install_dir }}"
