---
- name: Download Python 2.7.12
  get_url: dest=/tmp/python27.tar.xz
    url="https://www.python.org/ftp/python/2.7.12/Python-2.7.12.tar.xz"

- name: Extract Python source
  command: tar xf python27.tar.xz
    chdir=/tmp
    creates=/tmp/python-2.7.12

- name: Configure Python
  shell: ./configure
  args:
    chdir: /tmp/python-2.7.12

- name: Make Python
  shell: make
  args:
    chdir: /tmp/python-2.7.12

- name: Install Python
  sudo: true
  shell: make install
  args:
    chdir: /tmp/python-2.7.12
