---
- name: Download and extract Python 2.7.12
  unarchive:
    src="https://www.python.org/ftp/python/2.7.12/Python-2.7.12.tar.xz"
    dest=/tmp
    remote_src=yes

- name: Configure Python
  shell: ./configure
  args:
    chdir: /tmp/Python-2.7.12

- name: Make Python
  shell: make
  args:
    chdir: /tmp/Python-2.7.12

- name: Install Python
  sudo: true
  shell: make install
  args:
    chdir: /tmp/Python-2.7.12
