---
- name: generate password
  command: "openssl rand -base64 15"
  register: serverpass
  changed_when: False

- name: build servers
  clc_server:
    location: "{{ dc | d('') }}"
    group: "{{ group | d('Default Group') }}"
    network_id: "{{ network_id | d('') }}"
    count: "{{ srv_count | d(1) }}"
    name: "{{ srv_name | d('node') }}"
    cpu: "{{ srv_cpu | d(2)}}"
    memory: "{{ srv_mem | d(4) }}"
    additional_disks: "{{ srv_disks | d([])}}"
    template: "{{ srv_template | d('ubuntu-14-64') }}"
    password: "{{ serverpass.stdout }}"
    add_public_ip: "{{ srv_public | d(false) }}"
    public_ip_ports: "{{ srv_ports | d('') }}"
  register: clc

- name: inventory
  add_host:
    groups=servers
    name={{ item.name }}
    ansible_ssh_user=root
    ansible_ssh_host={{ item.ipAddresses[0].internal }}
    ansible_ssh_pass={{ serverpass.stdout }}
    publicip={{ item.publicip | d('') }}
  with_items: clc.servers
